repoURL: https://github.com/yamini-nagellaa/k8-ocp-argo-all.git
targetRevision: code
environment: dev #this might come from top
argocd_vault_plugin:
  name: argocd-vault-plugin-helm-custom
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: argo-learnings
  argocd_namespace: argocd
  nginx_app_namespace: nginx-ns
  node_app_namespace: nodeapp-ns
nginx_app_service:
  replicas: 1
