apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: nodeapp-ns
  labels:
    app: nodeapp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-app
  template:
    metadata:
      labels:
        app: nodeapp-app
    spec:
      containers:
      - name: nodeapp
        image: yamininagella1208/cont-i-img:v3
