---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: nginx-ns
    server: https://kubernetes.default.svc
  project: argo-learnings
  source:
    plugin:
        name: argocd-vault-plugin-helm-custom        
        env:
        - name: HELM_VALUES
          value: --values values.yaml
        - name: HELM_ARGS
          value: >-
            --set nginx_app_service.replicas={{.Values.nginx_app_service.replicas}}
    path: resources/nginxapp
    repoURL: https://github.com/yamini-nagellaa/k8-ocp-argo-all.git
    targetRevision: code
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
