---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: nodeapp-ns
    server: https://kubernetes.default.svc
  project: argo-learnings
  source:
    path: resources/nodeapp
    repoURL: https://github.com/yamini-nagellaa/k8-ocp-argo-all.git
    targetRevision: code
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
